// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axhsfqoxrlzjclqezhvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aHNmcW94cmx6amNscWV6aHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzMyNzUsImV4cCI6MjA2Mzg0OTI3NX0.dVBoEImHZR0NEoDJ2C5CFvmozAj4HeFoLn4FH8YS1Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);